version: '3'

services:
  db:
    image: mongo:4.4.1
  web:
    build: .
    command: npm start
    ports:
      - '8000:8000'
    depends_on:
      - db
      - rabbit
  rabbit:
    image: rabbitmq:3.8.9
